ENT.Type = "ai"
ENT.Base = "base_ai"
ENT.Spawnable = true
ENT.AdminSpawnable = true
ENT.PrintName = "Käufer"
ENT.Author = "Yolo"
ENT.Information = "info"
ENT.Category = "Yolo's Stuff"
ENT.DisableDuplicator = false
ENT.AutomaticFrameAdvance = true
